version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
        - 6379:6379
